import { sql } from "drizzle-orm";
import { boolean, index, integer, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { user } from "./auth";

/**
 * App-owned workflow state behind the account settings pages. PostgreSQL is
 * the authority for both lifecycles; Redis only throttles. Rows outlive their
 * workflow for support context, but every secret-bearing column is erased the
 * moment a request leaves its active state.
 */

export const EMAIL_CHANGE_KINDS = ["change", "correction"] as const;
export type EmailChangeKind = (typeof EMAIL_CHANGE_KINDS)[number];

export const EMAIL_CHANGE_STATES = [
  "awaiting_current",
  "awaiting_new_address",
  "awaiting_new",
  "completed",
  "cancelled",
  "expired",
] as const;
export type EmailChangeState = (typeof EMAIL_CHANGE_STATES)[number];

/** The states in which a request may still authorize a step. */
export const ACTIVE_EMAIL_CHANGE_STATES = [
  "awaiting_current",
  "awaiting_new_address",
  "awaiting_new",
] as const satisfies readonly EmailChangeState[];

export const EMAIL_CHANGE_CANCEL_REASONS = [
  "user",
  "replaced",
  "credentials",
  "admin_change",
  "banned",
  /** The accounts involved changed: the original address became verified, or the destination was taken. */
  "account_changed",
] as const;
export type EmailChangeCancelReason = (typeof EMAIL_CHANGE_CANCEL_REASONS)[number];

/**
 * One request per lifecycle, `change` for a verified address (two mailbox
 * proofs) or `correction` for an unverified one (the corrected mailbox only).
 * Token columns hold SHA-256 digests of the emailed link tokens; the
 * generation counters let a resend supersede an earlier link without a race.
 */
export const emailChangeRequest = pgTable(
  "email_change_request",
  {
    /** Generated by the application (`randomUUID`), never by the client. */
    id: uuid("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    kind: text("kind", { enum: EMAIL_CHANGE_KINDS }).notNull(),
    state: text("state", { enum: EMAIL_CHANGE_STATES }).notNull(),
    originalEmail: text("original_email").notNull(),
    newEmail: text("new_email"),
    createdAt: timestamp("created_at").notNull(),
    /** Exactly `createdAt` + 24 hours; never extended. */
    expiresAt: timestamp("expires_at").notNull(),
    /** Metadata binding the initial proof to the session that supplied it; not a credential. */
    initiatingSessionId: text("initiating_session_id").notNull(),
    currentConfirmedAt: timestamp("current_confirmed_at"),
    newConfirmedAt: timestamp("new_confirmed_at"),
    currentTokenHash: text("current_token_hash"),
    newTokenHash: text("new_token_hash"),
    currentTokenGeneration: integer("current_token_generation").notNull().default(0),
    newTokenGeneration: integer("new_token_generation").notNull().default(0),
    completedAt: timestamp("completed_at"),
    cancelledAt: timestamp("cancelled_at"),
    cancelReason: text("cancel_reason", { enum: EMAIL_CHANGE_CANCEL_REASONS }),
    /** Workflow status: completion committed but the sessions were not yet confirmed revoked. */
    sessionRevocationPending: boolean("session_revocation_pending").notNull().default(false),
  },
  (table) => [
    uniqueIndex("email_change_request_current_token_hash_idx")
      .on(table.currentTokenHash)
      .where(sql`${table.currentTokenHash} IS NOT NULL`),
    uniqueIndex("email_change_request_new_token_hash_idx")
      .on(table.newTokenHash)
      .where(sql`${table.newTokenHash} IS NOT NULL`),
    index("email_change_request_user_created_idx").on(table.userId, table.createdAt),
    uniqueIndex("email_change_request_active_user_idx")
      .on(table.userId)
      .where(sql`${table.state} IN ('awaiting_current', 'awaiting_new_address', 'awaiting_new')`),
  ],
);

export const AUTHENTICATOR_SETUP_KINDS = ["enroll", "replace"] as const;
export type AuthenticatorSetupKind = (typeof AUTHENTICATOR_SETUP_KINDS)[number];

export const AUTHENTICATOR_SETUP_STATES = ["pending", "completed", "cancelled", "expired"] as const;
export type AuthenticatorSetupState = (typeof AUTHENTICATOR_SETUP_STATES)[number];

/**
 * A staged authenticator setup: an optional first enrollment (the pending
 * factor lives in the provider's row, unverified) or a replacement (the new
 * secret is staged here, encrypted, while the current factor stays active).
 * One pending attempt per user, ten minutes to prove the new authenticator.
 */
export const authenticatorSetupRequest = pgTable(
  "authenticator_setup_request",
  {
    id: uuid("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    initiatingSessionId: text("initiating_session_id").notNull(),
    kind: text("kind", { enum: AUTHENTICATOR_SETUP_KINDS }).notNull(),
    state: text("state", { enum: AUTHENTICATOR_SETUP_STATES }).notNull(),
    createdAt: timestamp("created_at").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    /** The provider factor row this attempt is bound to (the pending row for enrollment, the active one for replacement). */
    currentFactorId: text("current_factor_id").notNull(),
    /** SHA-256 of that row's encrypted secret at initiation; a changed factor invalidates the attempt. */
    currentFactorFingerprint: text("current_factor_fingerprint").notNull(),
    /** The account's security version once the initiation proofs passed. */
    authorizedSecurityVersion: integer("authorized_security_version").notNull(),
    /** Replacement only: the staged secret, encrypted with the provider's secret. */
    replacementSecret: text("replacement_secret"),
    completedAt: timestamp("completed_at"),
    cancelledAt: timestamp("cancelled_at"),
  },
  (table) => [
    index("authenticator_setup_request_user_created_idx").on(table.userId, table.createdAt),
    uniqueIndex("authenticator_setup_request_pending_user_idx")
      .on(table.userId)
      .where(sql`${table.state} = 'pending'`),
  ],
);
