-- Account settings: the email-change / correction request table, the staged
-- authenticator setup table, and the two server-owned user columns behind
-- operation-grant invalidation (security_version) and the post-email-change
-- revocation barrier (session_revocation_pending).
--
-- Generated by drizzle-kit from src/lib/db/schema; reviewed to contain only
-- these changes. The hand-written user_admin_* indexes from 0004 are not
-- known to drizzle-kit and are untouched. Partial unique indexes use only
-- immutable predicates (no now()).
CREATE TABLE "authenticator_setup_request" (
	"id" uuid PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"initiating_session_id" text NOT NULL,
	"kind" text NOT NULL,
	"state" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"expires_at" timestamp NOT NULL,
	"current_factor_id" text NOT NULL,
	"current_factor_fingerprint" text NOT NULL,
	"authorized_security_version" integer NOT NULL,
	"replacement_secret" text,
	"completed_at" timestamp,
	"cancelled_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "email_change_request" (
	"id" uuid PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"kind" text NOT NULL,
	"state" text NOT NULL,
	"original_email" text NOT NULL,
	"new_email" text,
	"created_at" timestamp NOT NULL,
	"expires_at" timestamp NOT NULL,
	"initiating_session_id" text NOT NULL,
	"current_confirmed_at" timestamp,
	"new_confirmed_at" timestamp,
	"current_token_hash" text,
	"new_token_hash" text,
	"current_token_generation" integer DEFAULT 0 NOT NULL,
	"new_token_generation" integer DEFAULT 0 NOT NULL,
	"completed_at" timestamp,
	"cancelled_at" timestamp,
	"cancel_reason" text,
	"session_revocation_pending" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
ALTER TABLE "user" ADD COLUMN "security_version" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "user" ADD COLUMN "session_revocation_pending" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "authenticator_setup_request" ADD CONSTRAINT "authenticator_setup_request_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "email_change_request" ADD CONSTRAINT "email_change_request_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "authenticator_setup_request_user_created_idx" ON "authenticator_setup_request" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "authenticator_setup_request_pending_user_idx" ON "authenticator_setup_request" USING btree ("user_id") WHERE "authenticator_setup_request"."state" = 'pending';--> statement-breakpoint
CREATE UNIQUE INDEX "email_change_request_current_token_hash_idx" ON "email_change_request" USING btree ("current_token_hash") WHERE "email_change_request"."current_token_hash" IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "email_change_request_new_token_hash_idx" ON "email_change_request" USING btree ("new_token_hash") WHERE "email_change_request"."new_token_hash" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "email_change_request_user_created_idx" ON "email_change_request" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "email_change_request_active_user_idx" ON "email_change_request" USING btree ("user_id") WHERE "email_change_request"."state" IN ('awaiting_current', 'awaiting_new_address', 'awaiting_new');