-- Logs module (app/(LogsModule)): email_log (one row per sending attempt) and
-- staff_log (one row per staff action).
--
-- Prerequisites, the same as the repository baseline (compose.yml runs
-- PostgreSQL 18):
--   * PostgreSQL 18 or later: the shared ID default is the built-in uuidv7().
--   * The pg_trgm extension, already installed by 0004 for the user list; the
--     statement below is a no-op then. It needs a role that may create
--     extensions when it is missing; the migration fails loudly otherwise.
--
-- Generated by drizzle-kit from src/lib/db/schema/logs.ts, then extended by
-- hand with the extension statement above the tables and the triggers at the
-- end. drizzle-kit knows neither; preserve them when regenerating.
-- email_log references only itself (the retry chain, ON DELETE RESTRICT).
-- staff_log references the acting user (ON DELETE RESTRICT) and points at its
-- resource by type and ID without a foreign key. Index creation is
-- transactional, which is fine for these new, empty tables.
CREATE EXTENSION IF NOT EXISTS pg_trgm;
--> statement-breakpoint
CREATE TABLE "email_log" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"record_key" varchar(200) NOT NULL,
	"input_digest" char(64) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"started_at" timestamp with time zone NOT NULL,
	"completed_at" timestamp with time zone,
	"recipient_email" varchar(254) NOT NULL,
	"recipient_user_id" varchar(128),
	"recipient_label" varchar(200),
	"subject" varchar(500) NOT NULL,
	"content_text" text NOT NULL,
	"status" varchar(16) DEFAULT 'sending' NOT NULL,
	"provider" varchar(64),
	"provider_message_id" varchar(200),
	"error_code" varchar(100),
	"error_message" text,
	"stack_trace" text,
	"original_log_id" uuid,
	"previous_attempt_id" uuid,
	"attempt_number" integer NOT NULL,
	"requester_kind" varchar(16) NOT NULL,
	"requester_id" varchar(128),
	"requester_label" varchar(200) NOT NULL,
	"request_id" varchar(128) NOT NULL,
	"redaction_version" smallint DEFAULT 1 NOT NULL,
	"completion_digest" char(64),
	"search_text" text NOT NULL,
	CONSTRAINT "email_log_record_key_key" UNIQUE("record_key"),
	CONSTRAINT "email_log_status_check" CHECK ("email_log"."status" IN ('sending', 'accepted', 'failed', 'unknown')),
	CONSTRAINT "email_log_requester_check" CHECK (("email_log"."requester_kind" = 'user' AND "email_log"."requester_id" IS NOT NULL AND "email_log"."requester_id" <> '')
        OR ("email_log"."requester_kind" = 'anonymous' AND "email_log"."requester_id" IS NULL AND "email_log"."requester_label" = 'Anonymous')),
	CONSTRAINT "email_log_chain_check" CHECK (("email_log"."original_log_id" IS NULL AND "email_log"."previous_attempt_id" IS NULL AND "email_log"."attempt_number" = 1)
        OR ("email_log"."original_log_id" IS NOT NULL AND "email_log"."previous_attempt_id" IS NOT NULL
          AND "email_log"."original_log_id" <> "email_log"."id" AND "email_log"."previous_attempt_id" <> "email_log"."id"
          AND "email_log"."attempt_number" > 1)),
	CONSTRAINT "email_log_completion_check" CHECK (("email_log"."status" = 'sending' AND "email_log"."completed_at" IS NULL AND "email_log"."completion_digest" IS NULL)
        OR ("email_log"."status" <> 'sending' AND "email_log"."completed_at" IS NOT NULL
          AND "email_log"."completed_at" >= "email_log"."started_at" AND "email_log"."completion_digest" IS NOT NULL)),
	CONSTRAINT "email_log_recipient_email_check" CHECK ("email_log"."recipient_email" <> '' AND "email_log"."recipient_email" = lower("email_log"."recipient_email")),
	CONSTRAINT "email_log_text_check" CHECK ("email_log"."record_key" <> '' AND "email_log"."requester_label" <> '' AND "email_log"."request_id" <> ''
        AND "email_log"."subject" <> '' AND "email_log"."content_text" <> ''
        AND octet_length("email_log"."content_text") <= 131072
        AND ("email_log"."error_message" IS NULL OR char_length("email_log"."error_message") <= 4000)
        AND ("email_log"."stack_trace" IS NULL OR octet_length("email_log"."stack_trace") <= 32768)),
	CONSTRAINT "email_log_digest_check" CHECK ("email_log"."input_digest" ~ '^[0-9a-f]{64}$'
        AND ("email_log"."completion_digest" IS NULL OR "email_log"."completion_digest" ~ '^[0-9a-f]{64}$')),
	CONSTRAINT "email_log_redaction_version_check" CHECK ("email_log"."redaction_version" >= 1)
);
--> statement-breakpoint
CREATE TABLE "staff_log" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"actor_id" text NOT NULL,
	"action" varchar(150) NOT NULL,
	"resource_type" varchar(64) NOT NULL,
	"resource_id" varchar(128) NOT NULL,
	"message" jsonb NOT NULL,
	"message_text" text NOT NULL,
	CONSTRAINT "staff_log_action_check" CHECK ("staff_log"."action" ~ '^[a-z][a-z0-9_.-]{0,149}$'),
	CONSTRAINT "staff_log_resource_check" CHECK ("staff_log"."resource_type" <> '' AND "staff_log"."resource_id" <> ''),
	CONSTRAINT "staff_log_message_check" CHECK (jsonb_typeof("staff_log"."message") = 'array' AND jsonb_array_length("staff_log"."message") >= 1
        AND "staff_log"."message_text" <> '')
);
--> statement-breakpoint
ALTER TABLE "email_log" ADD CONSTRAINT "email_log_original_log_id_email_log_id_fk" FOREIGN KEY ("original_log_id") REFERENCES "public"."email_log"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "email_log" ADD CONSTRAINT "email_log_previous_attempt_id_email_log_id_fk" FOREIGN KEY ("previous_attempt_id") REFERENCES "public"."email_log"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "staff_log" ADD CONSTRAINT "staff_log_actor_id_user_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."user"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "email_log_started_at_id_idx" ON "email_log" USING btree ("started_at" DESC NULLS FIRST,"id" DESC NULLS FIRST);--> statement-breakpoint
CREATE INDEX "email_log_status_started_at_id_idx" ON "email_log" USING btree ("status","started_at" DESC NULLS FIRST,"id" DESC NULLS FIRST);--> statement-breakpoint
CREATE INDEX "email_log_recipient_user_started_at_id_idx" ON "email_log" USING btree ("recipient_user_id","started_at" DESC NULLS FIRST,"id" DESC NULLS FIRST);--> statement-breakpoint
CREATE INDEX "email_log_recipient_email_started_at_id_idx" ON "email_log" USING btree ("recipient_email","started_at" DESC NULLS FIRST,"id" DESC NULLS FIRST);--> statement-breakpoint
CREATE UNIQUE INDEX "email_log_chain_attempt_idx" ON "email_log" USING btree ("original_log_id","attempt_number");--> statement-breakpoint
CREATE INDEX "email_log_search_text_trgm_idx" ON "email_log" USING gin ("search_text" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "staff_log_created_at_id_idx" ON "staff_log" USING btree ("created_at" DESC NULLS FIRST,"id" DESC NULLS FIRST);--> statement-breakpoint
CREATE INDEX "staff_log_resource_id_created_at_id_idx" ON "staff_log" USING btree ("resource_id","created_at" DESC NULLS FIRST,"id" DESC NULLS FIRST);--> statement-breakpoint
CREATE INDEX "staff_log_resource_type_created_at_id_idx" ON "staff_log" USING btree ("resource_type","created_at" DESC NULLS FIRST,"id" DESC NULLS FIRST);--> statement-breakpoint
CREATE INDEX "staff_log_actor_created_at_id_idx" ON "staff_log" USING btree ("actor_id","created_at" DESC NULLS FIRST,"id" DESC NULLS FIRST);--> statement-breakpoint
CREATE INDEX "staff_log_action_created_at_id_idx" ON "staff_log" USING btree ("action","created_at" DESC NULLS FIRST,"id" DESC NULLS FIRST);--> statement-breakpoint
CREATE INDEX "staff_log_message_text_trgm_idx" ON "staff_log" USING gin ("message_text" gin_trgm_ops);
--> statement-breakpoint
-- An email attempt's initiation snapshot never changes after insertion; only
-- the status/observation columns written by completeEmailLog may. Status moves
-- sending -> accepted | failed | unknown, and unknown -> accepted | failed
-- once; accepted and failed are final.
CREATE FUNCTION "email_log_guard_update"() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF (NEW."id", NEW."record_key", NEW."input_digest", NEW."created_at", NEW."started_at",
      NEW."recipient_email", NEW."recipient_user_id", NEW."recipient_label", NEW."subject",
      NEW."content_text", NEW."provider", NEW."original_log_id", NEW."previous_attempt_id",
      NEW."attempt_number", NEW."requester_kind", NEW."requester_id", NEW."requester_label",
      NEW."request_id", NEW."redaction_version", NEW."search_text")
     IS DISTINCT FROM
     (OLD."id", OLD."record_key", OLD."input_digest", OLD."created_at", OLD."started_at",
      OLD."recipient_email", OLD."recipient_user_id", OLD."recipient_label", OLD."subject",
      OLD."content_text", OLD."provider", OLD."original_log_id", OLD."previous_attempt_id",
      OLD."attempt_number", OLD."requester_kind", OLD."requester_id", OLD."requester_label",
      OLD."request_id", OLD."redaction_version", OLD."search_text") THEN
    RAISE EXCEPTION 'email_log initiation columns are immutable'
      USING ERRCODE = 'integrity_constraint_violation';
  END IF;
  IF NOT ((OLD."status" = 'sending' AND NEW."status" IN ('accepted', 'failed', 'unknown'))
       OR (OLD."status" = 'unknown' AND NEW."status" IN ('accepted', 'failed'))) THEN
    RAISE EXCEPTION 'email_log status % cannot change to %', OLD."status", NEW."status"
      USING ERRCODE = 'integrity_constraint_violation';
  END IF;
  RETURN NEW;
END;
$$;
--> statement-breakpoint
CREATE TRIGGER "email_log_guard_update" BEFORE UPDATE ON "email_log"
  FOR EACH ROW EXECUTE FUNCTION "email_log_guard_update"();
--> statement-breakpoint
-- The staff log is append-only: an entry is never edited or removed.
CREATE FUNCTION "staff_log_forbid_change"() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'staff_log is append-only'
    USING ERRCODE = 'integrity_constraint_violation';
END;
$$;
--> statement-breakpoint
CREATE TRIGGER "staff_log_forbid_change" BEFORE UPDATE OR DELETE ON "staff_log"
  FOR EACH ROW EXECUTE FUNCTION "staff_log_forbid_change"();
